<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Property search_w100 prop-max</name>
   <tag></tag>
   <elementGuidId>d5b19944-fcaa-4bc4-b25b-d6a550bd11ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[@id='page']/form[@id='mainform']/div[7]/div[1]/div[2]/div[1]/div[1]/div[3]/div[1]/aside[1]/div[1]/div[2]/ul[1]/li[1]/div[2]/div[1]/div[3]/input[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.w100.prop-max</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w100 prop-max</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Max</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1.87</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original</name>
      <type>Main</type>
      <value>1.87</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;row row_tds_product_datasheet2&quot;]/div[@class=&quot;col col1 v2&quot;]/div[@class=&quot;box_with_border&quot;]/div[@class=&quot;v2&quot;]/div[@class=&quot;row product-selector&quot;]/aside[@class=&quot;search-components v2 col  small-hidden  bgc11  zone1&quot;]/div[@class=&quot;filter closed active_filter&quot;]/div[@class=&quot;pl10 pr10 w100&quot;]/ul[@class=&quot;pa0 ma0 lsn filtres_actifs&quot;]/li[@class=&quot;filtres_actifsLi mode_write&quot;]/div[@class=&quot;ma0 mt10 write&quot;]/div[@class=&quot;row  mb10&quot;]/div[@class=&quot;col w50&quot;]/input[@class=&quot;w100 prop-max&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='1.87']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div[2]/div/div/div[3]/div/aside/div/div[2]/ul/li/div[2]/div/div[3]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
   </webElementXpaths>
</WebElementEntity>
