<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Property search_icon-crayon fs14</name>
   <tag></tag>
   <elementGuidId>80273f35-d703-4cf0-b118-4b8df7d33b00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div[2]/div/div/div[3]/div/aside/div/div[2]/ul/li/div/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.icon-crayon.fs14</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-crayon fs14</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;row row_tds_product_datasheet2&quot;]/div[@class=&quot;col col1 v2&quot;]/div[@class=&quot;box_with_border&quot;]/div[@class=&quot;v2&quot;]/div[@class=&quot;row product-selector&quot;]/aside[@class=&quot;search-components v2 col  small-hidden  bgc11  zone1&quot;]/div[@class=&quot;filter closed active_filter&quot;]/div[@class=&quot;pl10 pr10 w100&quot;]/ul[@class=&quot;pa0 ma0 lsn filtres_actifs&quot;]/li[@class=&quot;filtres_actifsLi&quot;]/div[@class=&quot;read&quot;]/a[@class=&quot;modifier tdn pa10 c9&quot;]/span[@class=&quot;icon-crayon fs14&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div[2]/div/div/div[3]/div/aside/div/div[2]/ul/li/div/a/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/a/span</value>
   </webElementXpaths>
</WebElementEntity>
