<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_Search</name>
   <tag></tag>
   <elementGuidId>348176b6-2422-4b5f-b909-824d64dd4fb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='productSearch']/div/div[2]/div[6]/div[2]/div/div/div/div[5]/div/a/strong</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.col.fs14.c0.bgc10.rounded5.txtcenter.h36p.vam.tdn.bt-search.a-filter-property > strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productSearch&quot;)/div[@class=&quot;bc1 bw2&quot;]/div[@class=&quot;search_hp&quot;]/div[@class=&quot;w100&quot;]/div[@class=&quot;form-group w100 center mt10&quot;]/div[@class=&quot;mb30&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;property_form&quot;]/div[@class=&quot;zone5 mt10&quot;]/div[@class=&quot;row w210p right&quot;]/a[@class=&quot;col fs14 c0 bgc10 rounded5 txtcenter h36p vam tdn bt-search a-filter-property&quot;]/strong[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='productSearch']/div/div[2]/div[6]/div[2]/div/div/div/div[5]/div/a/strong</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[2]/following::strong[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='torr'])[1]/following::strong[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Search']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/a/strong</value>
   </webElementXpaths>
</WebElementEntity>
