<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__relationship</name>
   <tag></tag>
   <elementGuidId>d0df9281-b8db-4963-811f-315fd9bd59ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ctl06_content_1_bodycontent_1_twoleftcol_0_form_6F50949906574A72B3B38D4143E75978_field_92BB71CF36CA43FE9AD2BD88156DEC58']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl06_content_1_bodycontent_1_twoleftcol_0_form_6F50949906574A72B3B38D4143E75978_field_92BB71CF36CA43FE9AD2BD88156DEC58</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl06$content_1$bodycontent_1$twoleftcol_0$form_6F50949906574A72B3B38D4143E75978$field_92BB71CF36CA43FE9AD2BD88156DEC58</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl06_content_1_bodycontent_1_twoleftcol_0_form_6F50949906574A72B3B38D4143E75978_field_92BB71CF36CA43FE9AD2BD88156DEC58</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>float project</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-maxlength</name>
      <type>Main</type>
      <value>2500</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-maxlength-message</name>
      <type>Main</type>
      <value>What kind of relationship are you ready to consider with the seeker? must have no more than 2500 characters.</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>What kind of relationship are you ready to consider with the seeker</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-title</name>
      <type>Main</type>
      <value>What kind of relationship are you ready to consider with the seeker?</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-errors-container</name>
      <type>Main</type>
      <value>#error-list-0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-required-message</name>
      <type>Main</type>
      <value>Please type your What kind of relationship are you ready to consider with the seeker?</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-required</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-group</name>
      <type>Main</type>
      <value>f0g1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-id</name>
      <type>Main</type>
      <value>4347</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl06_content_1_bodycontent_1_twoleftcol_0_form_6F50949906574A72B3B38D4143E75978_field_92BB71CF36CA43FE9AD2BD88156DEC58&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ctl06_content_1_bodycontent_1_twoleftcol_0_form_6F50949906574A72B3B38D4143E75978_field_92BB71CF36CA43FE9AD2BD88156DEC58']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl06_content_1_bodycontent_1_twoleftcol_0_form_6F50949906574A72B3B38D4143E75978_field_92BB71CF36CA43FE9AD2BD88156DEC58_scope']/div[2]/textarea</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/textarea</value>
   </webElementXpaths>
</WebElementEntity>
