<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>drop_Down_Company_Activity</name>
   <tag></tag>
   <elementGuidId>41228138-7e54-4e53-81ca-98d633748050</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/div[2]/form[1]/div[3]/div[1]/div[3]/div[1]/div[2]/div[4]/div[1]/div[2]/div[1]/div[1]/div[2]/div[7]/div[2]/select[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
