<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Read More_icon-datasheet-png</name>
   <tag></tag>
   <elementGuidId>9a873733-fe35-47b3-85b1-878c9e4b3941</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div[3]/div/div/div[6]/div/div/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.icon-datasheet-png</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-datasheet-png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;row row_tds_product_datasheet2&quot;]/div[@class=&quot;col col1 v2&quot;]/div[@class=&quot;box_with_corner&quot;]/div[@class=&quot;box_buttons&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col col1&quot;]/a[@class=&quot;bt_cta_1 colorbox documentredirecturl cboxElement&quot;]/span[@class=&quot;icon-datasheet-png&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div[3]/div/div/div[6]/div/div/a/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/a/span</value>
   </webElementXpaths>
</WebElementEntity>
