<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__city_webinar</name>
   <tag></tag>
   <elementGuidId>1a9a0a7c-00cf-4b29-a4f6-390dce440d91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl06_content_1_bodycontent_1_twoleftcol_0_webinarform_0_form_07809FBC0CE745358D5A425E98BECE24_field_2F3C1D7B688047CFBCFA5AC7843F7743']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl06_content_1_bodycontent_1_twoleftcol_0_webinarform_0_form_07809FBC0CE745358D5A425E98BECE24_field_2F3C1D7B688047CFBCFA5AC7843F7743</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl06$content_1$bodycontent_1$twoleftcol_0$webinarform_0$form_07809FBC0CE745358D5A425E98BECE24$field_2F3C1D7B688047CFBCFA5AC7843F7743</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>256</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl06_content_1_bodycontent_1_twoleftcol_0_webinarform_0_form_07809FBC0CE745358D5A425E98BECE24_field_2F3C1D7B688047CFBCFA5AC7843F7743</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>float</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-maxlength</name>
      <type>Main</type>
      <value>256</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-maxlength-message</name>
      <type>Main</type>
      <value>City must have no more than 256 characters.</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>City</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-title</name>
      <type>Main</type>
      <value>City</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-errors-container</name>
      <type>Main</type>
      <value>#error-list-0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-required-message</name>
      <type>Main</type>
      <value>Please type your City</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-required</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-group</name>
      <type>Main</type>
      <value>f0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-id</name>
      <type>Main</type>
      <value>8458</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl06_content_1_bodycontent_1_twoleftcol_0_webinarform_0_form_07809FBC0CE745358D5A425E98BECE24_field_2F3C1D7B688047CFBCFA5AC7843F7743&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl06_content_1_bodycontent_1_twoleftcol_0_webinarform_0_form_07809FBC0CE745358D5A425E98BECE24_field_2F3C1D7B688047CFBCFA5AC7843F7743']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl06_content_1_bodycontent_1_twoleftcol_0_webinarform_0_form_07809FBC0CE745358D5A425E98BECE24_field_2F3C1D7B688047CFBCFA5AC7843F7743_scope']/div[2]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/input</value>
   </webElementXpaths>
</WebElementEntity>
